#!/bin/sh

echo "----------mount all in fstab----------------"
/bin/mount -a
mkdir -p /dev/pts
mount -t devpts devpts /dev/pts
echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s
echo "****************Hello Linux******************"
echo "Kernel Version: Linux v6.11-rc7"
echo "***********************************************"